---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: end-of-file-fixer
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
        args:
          - --format=parsable
          - --strict
        exclude: user-data.yaml
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        args:
          - --mapping=2
          - --sequence=4
          - --offset=2
          # Match .yamllint.yaml; we don't care about line-length.
          - --width=1200
        exclude: user-data.yaml
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.16.4
    hooks:
      - id: gitleaks
  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0
    hooks:
      - id: check-json5
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.7.1
    hooks:
      - id: editorconfig-checker
        alias: ec
